# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "rust-web-demo"
version = "0.1.0"
edition = "2021"
default-run = "demo"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
askama = { version = "0.12", default-features = false, features = ["with-axum", "mime", "mime_guess"] }
askama_axum = "0.3"
axum = "0.6"
dotenvy = "0.15"
mime_guess = "2"
once_cell = "1"
r2d2 = "0.8"
#r2d2_sqlite = "0.21"
r2d2_sqlite = { version = "0.21", git = "https://github.com/johnbcodes/r2d2-sqlite.git", branch = "rusqlite-upgrade" }
rusqlite = { version = "0.29", features = ["bundled", "serde_json"] }
#rusqlite_migration = "1"
rusqlite_migration = { version = "1.1.0-alpha.2", git = "https://github.com/johnbcodes/rusqlite_migration.git", branch = "rusqlite-upgrade" }
rust-embed = { version = "6", features = ["interpolate-folder-path"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.4", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
