# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "demo-axum-hotwire-tailwind"
version = "0.1.0"
edition = "2021"
default-run = "demo"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
#askama = { version = "0.11", default-features = false, features = ["with-axum", "mime", "mime_guess"] }
askama = { git = "https://github.com/djc/askama", default-features = false, features = ["with-axum", "mime", "mime_guess"] }
#askama_axum = { version = "0.1" }
askama_axum = { git = "https://github.com/djc/askama" }
axum = { version = "0.5" }
dotenv = "0.15"
lazy_static = "1"
mime_guess = "2"
regex = "1.5"
rust-embed = "6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", features = [ "macros", "migrate", "offline", "postgres", "runtime-tokio-native-tls", "time" ] }
tokio = { version = "1", features = ["full"] }
time = "0.3"
tower-http = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
voca_rs = "1"