# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "rust-web-demo"
version = "0.1.0"
edition = "2021"
default-run = "demo"

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
askama = { version = "0.12", default-features = false, features = ["with-axum", "mime", "mime_guess"] }
askama_axum = "0.3"
axum = "0.6.11"
dotenvy = "0.15"
mime_guess = "2"
once_cell = "1"
r2d2 = "0.8"
r2d2_sqlite = "0.21"
rusqlite = { version = "0.28.0", features = ["bundled", "serde_json"] }
rusqlite_migration = "1"
rust-embed = { version = "6", features = ["interpolate-folder-path"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.4", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
fd-lock = "3.0"
regex = "1"
