version: "3.8"

services:
  web.app:
    build:
      context: .
    environment:
      - DATABASE_URL=sqlite:///data/demo.db
    ports:
      - "8080:8080"
    volumes:
      - db-data:/data

volumes:
  db-data:
