version: "3.8"

services:
  web.app:
    build:
      target: dev
    environment:
      - DATABASE_FILE=/data/demo.db
    ports:
      - "8080:8080"
    volumes:
      - db-data:/data

volumes:
  db-data:
