version: "3.8"

services:
  web.app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/db

volumes:
  db-data:
