name: Build
on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Compile web artifacts
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo check
        run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Compile web artifacts
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo test
        run: cargo test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Compile web artifacts
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Run cargo clippy on tests
        # TODO add pedantic checks back in -- -Dclippy::pedantic
        run: cargo clippy --tests -- -Dclippy::all

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check
